pagopa/rtd-ms-ingestor

- manifests/deployment.yml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/Transaction.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobApplicationAware.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandlerIntegration.java
- src/test/resources/application-test.yml
This PR proposes a way to configure Spring Cloud Stream to manage different topics and their access policies.
- Configuration of Spring Cloud via application properties.
- Integration test.
- Blob application aware stub.
This PR is needed to ingest on the queue rtd-trx transactions sent by acquirers.
> [CEN-1447] Connect queue rtd trx

- .github/CODEOWNERS
This PR proposes to add Tommaso Lencioni to the repository code owners.
> [CEN-1533] Add Tommaso Lencioni to code owners.

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAware.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
This PR integrates the process step that the blob undergoes, in the event handler.
- Add PROCESSED status in the blob.
- Integrates processing step in the message handler.
- Add integration tests with mocked blobs.
After the blob download step, the blob is processed and all the transactions within it are extracted.
The processing step must be integrated into the event handler.
Thanks to this changes the blob is first downloaded, then processed, following consequential steps in the handler.
> [CEN-1537] Integrate process logic in event handling

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAware.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAwareTest.java
This PR implements the local deletion of blob files.
- Local delete blob deletion mechanism.
- Unit tests.
After the remote deletion of the blob, the local files must be deleted to avoid clogging the instance.
> [CEN-1560] Implement local delete of blob files

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configuration/ThreadSafeHttpClient.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/HttpClientTest.java
This PR enabled the "TrustSelfSignedStrategy" in the creation of the HTTP client in order to allow the service to communicate with the internal APIM endpoint.
- Closable HTTP Client implementation bean.
- Unit test.
This change is required in order to connect the microservice to the endpoint.
> [CEN-1585] Create HTTP client with TrustSelfSignedStrategy 

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAware.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAwareTest.java
This PR fix an unwanted behaviour obtained while evaluating the URI of the incoming blobs.
The old regex was build for the decrypter microservice.
The ingestror microservice, instead, gathers the blobs from a well defined container.
- Change in blob URI regex.
- Adapt existing tests.
The app was evaluating wrong events, this change make it evaluate the right ones.
> [CEN-1586] Fix regex URI

- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAwareTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
After the fix of the URI regex, all the tests that used the old container name string must be changed.
- Fix tests with wrong container name.
Not adjusted tests failed due to wrong container's name.
> [CEN-1587] Fix test URI patter

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
This PR propose an improvement to logging during the download step of a blob.
- Add log in case of successful get.
- Refactor log in case of failed get.
- Rename "download" method to "get".
This change allows a better blob handling step reconstruction.
> [CEN-1577] Better blob GET log

- .pre-commit-config.yaml
- docker-compose.yaml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAware.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
A docker-compose file was added to run kafka locally. With this is easier test this service in a local environment. 
-add docker-compose file
-local test
> [RTD-939] add docker-compose to have kafka locally

- helm/rtd/values.yaml
- pom.xml
> chore: [RTD-107-] Disabled ingress and service creation

- Dockerfile
Inserted amazoncorretto:11 dockerfile
> [RTD-1210] solve CVEs 

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/infrastructure/IngestorQueryTest.java
Inserted a test for mongo records state != READY to check if the query works correctly
1. Added mongo test
2. Fix mongo exception message bug
> [RTD-1252] Added test and fix bug on mongo exception printed message

- .devops/cstar-rtd-code-review-pipelines.yml
This PR fix code review pipeline trigger
> fix: code review pipeline

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/EventDeadLetterQueueEvent.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
> [RTD-1244] Create dead letter queue consumer

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/DeadLetterQueueProcessor.java
Deleted trx logs.
To not flood of unuseful logs that make difficult the test/debugging session.
> [RTD-1349] deleted trx logs

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configuration/RepositoryConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configuration/ThreadSafeHttpClient.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/event/EventHandler.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/infrastructure/repositories/IngestorDAO.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/infrastructure/repositories/IngestorRepositoryImpl.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAware.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/FiscalCode.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/FiscalCodeConstraint.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/FiscalCodeValidator.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/Transaction.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/DeadLetterQueueProcessor.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/TransactionVerifier.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplicationTests.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configs/MongoDbTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configs/MongoDbTestConfig.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/infrastructure/IngestorQueryTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/BlobApplicationAwareTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/FiscalCodeTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/DeadLetterQueueProcessorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/HttpClientTest.java
> [RTD-1354] formatting files

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/model/FiscalCodeValidator.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
This PR is to fix the service breaking triggered by empty fiscal code case or empty line.
> [RTD-1338] manage empty fiscal code break

- .devops/cstar-rtd-deploy-pipelines.yml
- helm/rtd/.helmignore
- helm/rtd/Chart.yaml
- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
> Promote new claster PROD

- pom.xml
- src/main/resources/application.yml
> chore: add actuator to PROD

- helm/rtd/values.yaml
- pom.xml
> chore: update pom and helm

- helm/rtd/values.yaml
> fix: [RTD-1456] Fix AppInsights problem

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .releaserc.json
> chore: [RTD-1514] add release and pr-title files

- helm/rtd/Chart.lock
This PR proposes to add the chart.lock file to solve the related error in the deploy pipeline.
> chore: [RTD-1604] add chart.lock file

- src/main/resources/application.yml
This PR proposes a fix in the configuration of spring cloud stream.
> fix: [RTD-1666] fix application spring cloud

- .github/workflows/anchore.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- Dockerfile
This pins docker base image and github actions
> chore: [RTD-1739] Docker & Actions pinning

- Dockerfile
- pom.xml
This PR's purpose is about to run the container as no root user, updating  maven from 3.9.0 to 3.9.3 and updating ApplicationInsights-Java from 3.4.11 to 3.4.14
- Run the container as no root user
- Update  maven from 3.9.0 to 3.9.3
- Update ApplicationInsights-Java from 3.4.11 to 3.4.14
- Bump version
- Update spring-boot-starter-parent from 3.0.6 to 3.1.1
- Update spring-cloud from 2022.0.2 to 2022.0.3
- Update testcontainer from 1.18.0 to 1.18.3
> chore: [RTD-1809] change to no root container execution

- src/main/resources/application.yml
> chore: [RTD-1894] new evh rtd

- helm/rtd/values.yaml
This PR is about to fix no root container execution by adding security context in helm values.
> chore: [RTD-1884] add security context

- Dockerfile
- helm/rtd/values.yaml
- pom.xml
This PR is about updating dependencies and docker file image for running the service in the uat environment.
> Promote to UAT

- pom.xml
package | old version | new version
-- | -- | --
spring boot | 3.1.2 | 3.1.3
> chore: [RTD-1882] fix cve

- helm/rtd/values-prod.yaml
This PR enable to use new platform-events queue from PROD env
- remove of overridden prod properties to use the default ones
> chore: [RTD-1906] Update helm chart prod new platform-events evh

- helm/rtd/values-prod.yaml
> chore: deploy to Prod

- src/main/resources/application.yml
- src/test/resources/application-test.yml
This PR proposes to change URLs that `rtd-ms-ingestor` calls to update contracts information.
- change application.yaml (both prod and test)
> fix: [CHK-2773] change URL of wallet migration endpoints

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/EventProcessor.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/utils/Anonymizer.java
- src/main/resources/application.yml
- src/main/resources/logback.xml
- src/test/resources/WALLET.CONTRACTS.20240313.174811.001.json.pgp.0.decrypted
- src/test/resources/WALLET.CONTRACTS.20240402.103010.001.json.pgp.0.decrypted
- src/test/resources/logback.xml
> fix: [CHK-2922] Remove contract CREATE KO check 

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/EventProcessor.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/EventProcessorTest.java
> chore: [CHK-2923] Use one span per contract

- helm/rtd/values.yaml
- pom.xml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/RtdMsIngestorApplication.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configuration/WalletConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletService.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnectorTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletServiceTest.java
- src/test/resources/application-test.yml
> feat: add wallet rate limiter

- helm/rtd/values.yaml
> fix: threat rate limit and retries values as strings

- helm/rtd/values-prod.yaml
- helm/rtd/values.yaml
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/configuration/WalletConfiguration.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/BlobRestConnector.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletService.java
- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/utils/ApacheUtils.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/HttpClientTest.java
- src/test/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletServiceTest.java
- src/test/resources/application-test.yml
* make more parameters customizable
* improve logging error
* improve shutdown
* fix get blob missing error
* fix get blob missing error
> fix(migration): Kafka consumer & minors  (#125)

- src/main/resources/application.yml
> fix(migration): added kafka socket timeouts

- src/main/resources/application.yml
> added kafka socket timeouts (#133)

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletService.java
Substitute exponential backoff with random waiting times
> fix: Remove Exponential Backoff

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/wallet/WalletService.java
> fix: Remove Exponential Backoff (#149)

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/EventProcessor.java
> fix: Use standard method invokeAll and a local executor

- src/main/java/it/gov/pagopa/rtd/ms/rtdmsingestor/service/EventProcessor.java
> Use standard method invokeAll and a local executor (#152)

- helm/rtd/values-dev.yaml
- helm/rtd/values-prod.yaml
- helm/rtd/values-uat.yaml
- helm/rtd/values.yaml
* increased ram and added xmx and xms
* increased ram and added xmx and xms
> fix: increased ram and added xmx and xms (#167)
